name: Unity Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.20f1
          targetPlatform: StandaloneWindows64

