name: Unity Build

on: [push]

jobs:
  build:
    env:
        UNITY_PROJECT_PATH: ''
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-target: StandaloneLinux64
          - os: windows-latest
            build-target: StandaloneWindows64
          - os: macos-latest
            build-target: StandaloneOSX
    steps:
      - uses: buildalon/unity-action@v3
        name: ${{ matrix.build-target }}-Build
        with:
          editor-path: path/to/your/unity/editor/installation
          project-path: path/to/your/unity/project
          log-name: ${{ matrix.build-target }}-Build
          build-target: ${{ matrix.build-target }}
          args: -quit -nographics -batchmode